var wagerABI = [ 
	{ constant: false,
		inputs: [],
		name: 'renounceOwnership',
		outputs: [],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'function' },
	{ constant: true,
		inputs: [],
		name: 'owner',
		outputs: [ [Object] ],
		payable: false,
		stateMutability: 'view',
		type: 'function' },
	{ constant: false,
		inputs: [ [Object] ],
		name: 'transferOwnership',
		outputs: [],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'function' },
	{ inputs: [ [Object], [Object] ],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'constructor' },
	{ anonymous: false,
		inputs: [ [Object] ],
		name: 'OwnershipRenounced',
		type: 'event' },
	{ anonymous: false,
		inputs: [ [Object], [Object] ],
		name: 'OwnershipTransferred',
		type: 'event' },
	{ constant: false,
		inputs: [ [Object] ],
		name: 'betting',
		outputs: [],
		payable: true,
		stateMutability: 'payable',
		type: 'function' },
	{ constant: false,
		inputs: [ [Object] ],
		name: 'withdraw',
		outputs: [],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'function' },
	{ constant: true,
		inputs: [ [Object] ],
		name: 'totalWager',
		outputs: [ [Object] ],
		payable: false,
		stateMutability: 'view',
		type: 'function' },
	{ constant: true,
		inputs: [ [Object] ],
		name: 'ratioForWinner',
		outputs: [ [Object] ],
		payable: false,
		stateMutability: 'view',
		type: 'function' } 
]
